logo:
  subtitle: 西安邮电大学MC兴趣交流团体|⛏ Cube of Posts

menubar:
  columns: 3
  items:
    - id: post
      title: 文章
      url: /
    - id: link
      title: 链接
      url: /link/
    - id: about
      title: 关于
      url: /about/

site_tree:
  home:
    rightbar: cop_skin

article:
  type: story

footer:
  sitemap:
    加入:
      - "[<i class='fa-brands fa-qq'></i> QQ群: 779877449](https://qm.qq.com/q/MllD9EItGw)"
      - "[<i class='fa-solid fa-cube'></i> 邮立方皮肤站](https://cop.imu.nm.cn/)"
      - "[<i class='fa-solid fa-medal'></i> Minecraft 高校联盟](https://www.mualliance.cn/)"
    探索:
      - "[<i class='fa-solid fa-server'></i> MUA 联合认证服务器](https://www.mualliance.cn/server)"
      - "[<i class='fa-solid fa-map-location-dot'></i> 高校 MC 组织地图](https://map.mualliance.cn/)"
    信息:
      - "[<i class='fa-regular fa-calendar-check'></i> 邮立方建立<uptime></uptime>](/about#%E5%A4%A7%E4%BA%8B%E8%AE%B0)"
      - "[<i class='fa-brands fa-github'></i> 网站仓库](https://github.com/pubsite/cube-of-posts-site)"
      - "[<i class='fa-solid fa-palette'></i> Hexo主题: Stellar](https://github.com/xaoxuu/hexo-theme-stellar)"
  content: ""

# style:
#   font-family:
#     logo: "'猫啃珠圆体', system-ui, sans-serif"
#   leftbar:
#     background-image: "url(https://images.unsplash.com/photo-1553356084-58ef4a67b2a7?w=100), linear-gradient(60deg, #cde, #8ac)"

inject:
  head:
    - <link rel="stylesheet" href="//lib.baomitu.com/font-awesome/6.5.1/css/all.min.css" media="none" onload="this.media='all'">
    - <link rel="stylesheet" href="https://chinese-fonts-cdn.deno.dev/packages/mkzyt/dist/猫啃珠圆体/result.css">
    - <link rel="stylesheet" href="/static/font.css">
    - <link rel="stylesheet" href="//thisis.host/static/patch.css">
    - <link rel="stylesheet" href="//thisis.host/static/patch-leftbar.css">
  script:
    - <script src="/static/uptime.js"></script>
